markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Denis Laliberté
url: http://denislaliberte.github.io/blog
description: todo description
twitter: denislaliberte
