markdown: rdiscount
permalink: /blog/posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Denis Laliberté
url: http://denislaliberte.github.io
description: todo description
twitter: denislaliberte
